#!/bin/bash
# Dummy script

logger -t "2.d start_polling" "Start 123Solar and meterN polling via bootstrap call"

sh -c "sleep 1 && curl -sS http://localhost/123solar/scripts/boot123s.php &"
sh -c "sleep 2 && curl -sS http://localhost/metern/scripts/bootmn.php &"
