#!/bin/bash
# hooks/build
# https://docs.docker.com/docker-cloud/builds/advanced/

echo "[***] Build hook running"

ALPINE_BRANCH=3.9

docker build . \
	--tag $IMAGE_NAME \
	--build-arg ALPINE_BRANCH=$ALPINE_BRANCH \
	--build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
	--build-arg VERSION=$(git describe --tags --always) \
	--build-arg VCS_REF=$(git rev-parse --short=7 HEAD)
