#!/bin/bash
# hooks/build
# https://docs.docker.com/docker-cloud/builds/advanced/

echo "[***] Build hook running"

ALPINE_BRANCH=3.9
RELEASE_123SOLAR=1.8.1
RELEASE_METERN=0.9.3

docker build . \
	--tag $IMAGE_NAME \
	--build-arg ALPINE_BRANCH=$ALPINE_BRANCH \
	--build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
	--build-arg RELEASE_123SOLAR=$RELEASE_123SOLAR \
	--build-arg RELEASE_METERN=$RELEASE_METERN \
	--build-arg VERSION=$(git describe --tags --always) \
	--build-arg VCS_REF=$(git rev-parse --abbrev-ref HEAD)