#!/bin/bash
# hooks/post_push
# https://docs.docker.com/docker-cloud/builds/advanced/

echo "### Tagging the build to \"latest\"... ###"

# Avoid "latest" tagging if master branch is pushed 
if [ "$SOURCE_BRANCH" != "master" ]; then
	docker tag $IMAGE_NAME $DOCKER_REPO:latest
	docker push $DOCKER_REPO:latest
fi
